
// Generated by https://quicktype.io

import { GithubUser } from "./github.user";

export interface GithubUsersResp {
  total_count:        number;
  incomplete_results: boolean;
  items:              GithubUser[];
}
